### ISSUE TITLE
File::ShareDir::Install

### ISSUE THREAD

**Issue by stuartskelton** [skx/chronicle2#42]
I just did a fresh install on one of my servers and I needed came up against a couple of problems, one of which should be fixed with #41.

However the other one, I am not sure how to go about fixing it (that means it will be very easy and I cant see it).

It has to do with `File::ShareDir::Install`. `File::ShareDir::Install` is sort of a special case as its also a pre-build requisite,its used in `perl Makefile.PL` step as well as the subsequent `make` steps.

Its almost like we need a pre-install install step.

Stuart

**Comment by skx** [comment]
I'd suggest installation via the debian package - if that isn't an option then I'd guess you're installing via CPAN?  And if so that should be handled as part of the cpan fetc/installation - with the update from #41.

Or am I missing something?

**Comment by stuartskelton** [comment]
Ok I may not have done a standard cpan install, I tend to use Cpanminus.

**Comment by skx** [comment]
This is resolved now - along with #41.
